/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#9cf2e8",
        "tertiary-fixed": "#bdece2",
        "error": "#ba1a1a",
        "on-primary-container": "#91d5ce",
        "inverse-on-surface": "#dff5f3",
        "surface-container-low": "#e1f8f6",
        "on-error-container": "#93000a",
        "outline-variant": "#bec9c7",
        "surface-container": "#dcf2f0",
        "surface-variant": "#d0e7e5",
        "on-secondary-fixed": "#00201d",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d0e7e5",
        "on-primary-fixed": "#00201e",
        "on-background": "#0a1f1e",
        "surface-tint": "#216963",
        "on-secondary-fixed-variant": "#00504a",
        "on-primary-fixed-variant": "#00504b",
        "surface-container-high": "#d6edeb",
        "inverse-primary": "#8fd3cc",
        "secondary-container": "#99efe5",
        "on-secondary-container": "#006f67",
        "on-tertiary-fixed": "#00201c",
        "outline": "#6f7977",
        "primary-fixed": "#abefe8",
        "inverse-surface": "#203433",
        "error-container": "#ffdad6",
        "secondary": "#006a63",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#a4d2c9",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0a1f1e",
        "secondary-fixed-dim": "#80d5cb",
        "surface": "#e7fefc",
        "primary-fixed-dim": "#8fd3cc",
        "on-tertiary-fixed-variant": "#224e47",
        "tertiary": "#17443e",
        "primary-container": "#115e59",
        "surface-dim": "#c8dfdc",
        "tertiary-container": "#305c55",
        "surface-bright": "#e7fefc",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "primary": "#004541",
        "tertiary-fixed-dim": "#a2d0c6",
        "background": "#e7fefc",
        "on-surface-variant": "#3f4947",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "3rem",
        "space-lg": "1.5rem",
        "margin-mobile": "1.25rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        "space-md": "1rem",
        "space-2xl": "4rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Newsreader", "serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "metric-md": ["Inter", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-hero": ["Newsreader", "serif"],
        "metric-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        sans: ["Inter", "sans-serif"],
        serif: ["Newsreader", "serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-hero-mobile": ["36px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "metric-md": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "600" }],
        "display-hero": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "metric-lg": ["36px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};